package com.grupo11.sistema_tele_pizza_backend.aplicacao;

import com.grupo11.sistema_tele_pizza_backend.aplicacao.requests.RegistrarClienteRequest;
import com.grupo11.sistema_tele_pizza_backend.aplicacao.responses.ClienteResponse;
import com.grupo11.sistema_tele_pizza_backend.dominio.dados.ClienteRepository;
import com.grupo11.sistema_tele_pizza_backend.dominio.entidades.Cliente;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

@Component
public class RegistrarClienteUC {

    private final ClienteRepository clienteRepository;

    @Autowired
    public RegistrarClienteUC(ClienteRepository clienteRepository) {
        this.clienteRepository = clienteRepository;
    }

    public ClienteResponse run(RegistrarClienteRequest request) {
        clienteRepository.findByEmail(request.getEmail()).ifPresent(c -> {
            throw new IllegalArgumentException("Email já cadastrado.");
        });

        Cliente novoCliente = new Cliente(
                null, // ID is generated by the repository
                request.getNome(),
                request.getCpf(),
                request.getCelular(),
                request.getEndereco(),
                request.getEmail(),
                request.getSenha() // In a real application, hash the password here
        );

        Cliente clienteSalvo = clienteRepository.save(novoCliente);
        return new ClienteResponse(clienteSalvo.getId());
    }
}